version: "3.9"
services:
  node1:
    build: .
    image: kademlia_node
    environment:
      - PORT=9001
    networks: [testnet]
  node2:
    image: kademlia_node
    environment:
      - PORT=9002
      - PEER=node1:9001
    networks: [testnet]
  node3:
    image: kademlia_node
    environment:
      - PORT=9003
      - PEER=node1:9001
    networks: [testnet]
  node4:
    image: kademlia_node
    environment:
      - PORT=9004
      - PEER=node1:9001
    networks: [testnet]
  node5:
    image: kademlia_node
    environment:
      - PORT=9005
      - PEER=node1:9001
    networks: [testnet]
  node6:
    image: kademlia_node
    environment:
      - PORT=9006
      - PEER=node1:9001
    networks: [testnet]
  node7:
    image: kademlia_node
    environment:
      - PORT=9007
      - PEER=node1:9001
    networks: [testnet]
  node8:
    image: kademlia_node
    environment:
      - PORT=9008
      - PEER=node1:9001
    networks: [testnet]
  node9:
    image: kademlia_node
    environment:
      - PORT=9009
      - PEER=node1:9001
    networks: [testnet]
  node10:
    image: kademlia_node
    environment:
      - PORT=9010
      - PEER=node1:9001
    networks: [testnet]
networks:
  testnet:
    driver: bridge
