services:
  node1:
    build: .
    image: kademlia_node
    environment:
      - PORT=9001
      - ISBOOTSTRAP=TRUE
      - ENABLECLI=TRUE
    stdin_open: true
    tty: true
    networks: [testnet]
  node2:
    image: kademlia_node
    environment:
      - PORT=9002
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    networks: [testnet]
  node3:
    image: kademlia_node
    environment:
      - PORT=9003
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    networks: [testnet]
  node4:
    image: kademlia_node
    environment:
      - PORT=9004
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    networks: [testnet]
  node5:
    image: kademlia_node
    environment:
      - PORT=9005
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    networks: [testnet]
  node6:
    image: kademlia_node
    environment:
      - PORT=9006
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    networks: [testnet]
  node7:
    image: kademlia_node
    environment:
      - PORT=9007
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    networks: [testnet]
  node8:
    image: kademlia_node
    environment:
      - PORT=9008
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    networks: [testnet]
  node9:
    image: kademlia_node
    environment:
      - PORT=9009
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    networks: [testnet]
  node10:
    image: kademlia_node
    environment:
      - PORT=9010
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    networks: [testnet]
networks:
  testnet:
    driver: bridge
