services:
  node1:
    build: .
    image: kademlia_node
    environment:
      - BOOTSTRAP=TRUE
      - PORT=1234
    networks: [testnet]
  node2:
    image: kademlia_node
    environment:
      - BOOTSTRAP=False
      - PEER=node1
      - PORT=5002
    networks: [testnet]
  node3:
    image: kademlia_node
    environment:
      - BOOTSTRAP=False
      - PEER=node1
      - PORT=5003
    networks: [testnet]
  node4:
    image: kademlia_node
    environment:
      - BOOTSTRAP=False
      - PEER=node1
      - PORT=5004
    networks: [testnet]
  node5:
    image: kademlia_node
    environment:
      - BOOTSTRAP=False
      - PEER=node1
      - PORT=5005
    networks: [testnet]
  node6:
    image: kademlia_node
    environment:
      - BOOTSTRAP=False
      - PEER=node1
      - PORT=5006
    networks: [testnet]
  node7:
    image: kademlia_node
    environment:
      - BOOTSTRAP=False
      - PEER=node1
      - PORT=5007
    networks: [testnet]
  node8:
    image: kademlia_node
    environment:
      - BOOTSTRAP=False
      - PEER=node1
      - PORT=5008
    networks: [testnet]
  node9:
    image: kademlia_node
    environment:
      - BOOTSTRAP=False
      - PEER=node1
      - PORT=5009
    networks: [testnet]
  node10:
    image: kademlia_node
    environment:
      - BOOTSTRAP=False
      - PEER=node1
      - PORT=5010
    networks: [testnet]
networks:
  testnet:
    driver: bridge
