services:
  node1:
    build: .
    image: kademlia_node
    environment:
      - PORT=9001
      - ISBOOTSTRAP=TRUE
    networks: [testnet]
  node2:
    image: kademlia_node
    environment:
      - PORT=9002
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    networks: [testnet]
networks:
  testnet:
    driver: bridge
