services:
  bootstrap:
    build: .
    image: kademlia_node
    environment:
      - PORT=9001
      - ISBOOTSTRAP=TRUE
      - ENABLECLI=TRUE
    deploy:
      replicas: 1
    networks:
      - testnet

  peer:
    image: kademlia_node
    environment:
      - ISBOOTSTRAP=FALSE
      - BOOTSTRAPNODE=bootstrap
      - ENABLECLI=TRUE
    depends_on:
      - bootstrap
    deploy:
      replicas: 49
    networks:
      - testnet

networks:
  testnet:
    driver: overlay
