services:
  node1:
    build: .
    image: kademlia_node
    environment:
      - BOOTSTRAP=TRUE
      - PORT=1234
    networks: [testnet]
  node2:
    image: kademlia_node
    environment:
      - BOOTSTRAP=False
      - PEER=node1
      - PORT=5002
    networks: [testnet]
networks:
  testnet:
    driver: bridge
