services:
  node1:
    build: .
    environment:
      - PORT=9001
      - ISBOOTSTRAP=TRUE
      - ENABLECLI=TRUE
    stdin_open: true
    tty: true
    networks: [testnet]
  node2:
    build: .
    environment:
      - PORT=9002
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    depends_on:
      - node1
    stdin_open: true
    tty: true
    networks: [testnet]
  node3:
    build: .
    environment:
      - PORT=9003
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    depends_on:
      - node1
    stdin_open: true
    tty: true
    networks: [testnet]
  node4:
    build: .
    environment:
      - PORT=9004
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    depends_on:
      - node1
    stdin_open: true
    tty: true
    networks: [testnet]
  node5:
    build: .
    environment:
      - PORT=9005
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    depends_on:
      - node1
    stdin_open: true
    tty: true
    networks: [testnet]
  node6:
    build: .
    environment:
      - PORT=9006
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    depends_on:
      - node1
    stdin_open: true
    tty: true
    networks: [testnet]
  node7:
    build: .
    environment:
      - PORT=9007
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    depends_on:
      - node1
    stdin_open: true
    tty: true
    networks: [testnet]
  node8:
    build: .
    environment:
      - PORT=9008
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    depends_on:
      - node1
    stdin_open: true
    tty: true
    networks: [testnet]
  node9:
    build: .
    environment:
      - PORT=9009
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    depends_on:
      - node1
    stdin_open: true
    tty: true
    networks: [testnet]
  node10:
    build: .
    environment:
      - PORT=9010
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    depends_on:
      - node1
    stdin_open: true
    tty: true
    networks: [testnet]
  node11:
    build: .
    environment:
      - PORT=9011
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    depends_on:
      - node1
    stdin_open: true
    tty: true
    networks: [testnet]
  node12:
    build: .
    environment:
      - PORT=9012
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    depends_on:
      - node1
    stdin_open: true
    tty: true
    networks: [testnet]
  node13:
    build: .
    environment:
      - PORT=9013
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    depends_on:
      - node1
    stdin_open: true
    tty: true
    networks: [testnet]
  node14:
    build: .
    environment:
      - PORT=9014
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    depends_on:
      - node1
    stdin_open: true
    tty: true
    networks: [testnet]
  node15:
    build: .
    environment:
      - PORT=9015
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    depends_on:
      - node1
    stdin_open: true
    tty: true
    networks: [testnet]
  node16:
    build: .
    environment:
      - PORT=9016
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    depends_on:
      - node1
    stdin_open: true
    tty: true
    networks: [testnet]
  node17:
    build: .
    environment:
      - PORT=9017
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    depends_on:
      - node1
    stdin_open: true
    tty: true
    networks: [testnet]
  node18:
    build: .
    environment:
      - PORT=9018
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    depends_on:
      - node1
    stdin_open: true
    tty: true
    networks: [testnet]
  node19:
    build: .
    environment:
      - PORT=9019
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    depends_on:
      - node1
    stdin_open: true
    tty: true
    networks: [testnet]
  node20:
    build: .
    environment:
      - PORT=9020
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    depends_on:
      - node1
    stdin_open: true
    tty: true
    networks: [testnet]
  node21:
    build: .
    environment:
      - PORT=9021
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    depends_on:
      - node1
    stdin_open: true
    tty: true
    networks: [testnet]
  node22:
    build: .
    environment:
      - PORT=9022
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    depends_on:
      - node1
    stdin_open: true
    tty: true
    networks: [testnet]
  node23:
    build: .
    environment:
      - PORT=9023
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    depends_on:
      - node1
    stdin_open: true
    tty: true
    networks: [testnet]
  node24:
    build: .
    environment:
      - PORT=9024
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    depends_on:
      - node1
    stdin_open: true
    tty: true
    networks: [testnet]
  node25:
    build: .
    environment:
      - PORT=9025
      - BOOTSTRAPNODE=node1
      - ISBOOTSTRAP=FALSE
    depends_on:
      - node1
    stdin_open: true
    tty: true
    networks: [testnet]
networks:
  testnet:
    driver: bridge
